-- 0008_action_type_replace_session.sql
--
-- Extends coach_chat_actions.action_type to allow 'replace_session' (used by the
-- new proposeReplaceSession tool — coach can replace a planned session with a
-- different workout instead of swapping it to rest + adding a new row).
--
-- Idempotent: drops any prior CHECK constraint on action_type before
-- recreating it with the expanded value list. Safe to re-run on every deploy.

DO $$
DECLARE
  ck_name text;
BEGIN
  -- Find any existing CHECK constraint on action_type and drop it.
  -- Name is auto-generated by Postgres so we look it up.
  FOR ck_name IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'coach_chat_actions'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%action_type%'
  LOOP
    EXECUTE format('ALTER TABLE coach_chat_actions DROP CONSTRAINT %I', ck_name);
  END LOOP;
END $$;

ALTER TABLE coach_chat_actions
  ADD CONSTRAINT coach_chat_actions_action_type_check
  CHECK (action_type IN (
    'soften_session',
    'swap_to_rest',
    'freeze_week',
    'record_symptom',
    'add_session',
    'replace_session'
  ));
